name: tegeltjeswijsheid-api
recipe: laravel
config:
  php: '7.4'
  via: nginx
  webroot: public
  database: mariadb
  cache: redis
  xdebug: true
services:
  mail:
    type: mailhog
    portforward: true
